from .logistic_regression import logistic_regression_weighting
from .uniform_weighting import uniform_weighting
from .neural_network_mmd_loss import neural_network_mmd_loss_weighting
from .ada_deboost import ada_deboost_weighting
from .maximum_representative_subsampling import repeated_MRS
from .kmm import kernel_mean_matching